/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
});
export const JobSource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'region' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'paymentLink' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const JobListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'salary' : IDL.Text,
  'applyUrl' : IDL.Text,
  'source' : IDL.Text,
  'jobType' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'company' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
});
export const Resume = IDL.Record({
  'id' : IDL.Text,
  'overallScore' : IDL.Nat,
  'jobDesc' : IDL.Text,
  'acceptanceRate' : IDL.Nat,
  'userId' : IDL.Principal,
  'improvements' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'fileName' : IDL.Text,
  'highlightSkills' : IDL.Vec(IDL.Text),
  'reportRequested' : IDL.Bool,
  'atsScore' : IDL.Nat,
  'linkedinTips' : IDL.Vec(IDL.Text),
  'competencies' : IDL.Vec(IDL.Text),
  'linkedinUrl' : IDL.Text,
  'pdfGenerated' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'profession' : IDL.Text,
  'approved' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaymentConfig = IDL.Record({
  'updatedAt' : IDL.Int,
  'pixKey' : IDL.Text,
  'paypalClientId' : IDL.Text,
  'mercadoPagoKey' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addJobSource' : IDL.Func([JobSource], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addVaga' : IDL.Func([JobListing], [], []),
  'approveTestimonial' : IDL.Func([IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteExpiredVagas' : IDL.Func([], [IDL.Nat], []),
  'deleteJobSource' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'getActiveJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
  'getLastUpdateTime' : IDL.Func([], [IDL.Int], ['query']),
  'getMyResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVagas' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAdmin' : IDL.Func([IDL.Principal], [], []),
  'requestReport' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'saveResume' : IDL.Func([Resume], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
  'triggerWeeklyUpdate' : IDL.Func([], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateJobSource' : IDL.Func([JobSource], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateResumeReportStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
  });
  const JobSource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'region' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'paymentLink' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'salary' : IDL.Text,
    'applyUrl' : IDL.Text,
    'source' : IDL.Text,
    'jobType' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'company' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
  });
  const Resume = IDL.Record({
    'id' : IDL.Text,
    'overallScore' : IDL.Nat,
    'jobDesc' : IDL.Text,
    'acceptanceRate' : IDL.Nat,
    'userId' : IDL.Principal,
    'improvements' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'fileName' : IDL.Text,
    'highlightSkills' : IDL.Vec(IDL.Text),
    'reportRequested' : IDL.Bool,
    'atsScore' : IDL.Nat,
    'linkedinTips' : IDL.Vec(IDL.Text),
    'competencies' : IDL.Vec(IDL.Text),
    'linkedinUrl' : IDL.Text,
    'pdfGenerated' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'profession' : IDL.Text,
    'approved' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaymentConfig = IDL.Record({
    'updatedAt' : IDL.Int,
    'pixKey' : IDL.Text,
    'paypalClientId' : IDL.Text,
    'mercadoPagoKey' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addJobSource' : IDL.Func([JobSource], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addVaga' : IDL.Func([JobListing], [], []),
    'approveTestimonial' : IDL.Func([IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteExpiredVagas' : IDL.Func([], [IDL.Nat], []),
    'deleteJobSource' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'getActiveJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
    'getLastUpdateTime' : IDL.Func([], [IDL.Int], ['query']),
    'getMyResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVagas' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAdmin' : IDL.Func([IDL.Principal], [], []),
    'requestReport' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'saveResume' : IDL.Func([Resume], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
    'triggerWeeklyUpdate' : IDL.Func([], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateJobSource' : IDL.Func([JobSource], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateResumeReportStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };