/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'summary' : string,
  'updatedAt' : bigint,
  'imageUrl' : string,
}
export interface JobListing {
  'id' : string,
  'title' : string,
  'postedAt' : bigint,
  'salary' : string,
  'applyUrl' : string,
  'source' : string,
  'jobType' : string,
  'area' : string,
  'city' : string,
  'company' : string,
  'badge' : [] | [string],
}
export interface JobSource {
  'id' : string,
  'url' : string,
  'region' : string,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'notes' : string,
}
export interface PaymentConfig {
  'updatedAt' : bigint,
  'pixKey' : string,
  'paypalClientId' : string,
  'mercadoPagoKey' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'paymentLink' : string,
  'category' : string,
  'price' : number,
}
export interface Resume {
  'id' : string,
  'overallScore' : bigint,
  'jobDesc' : string,
  'acceptanceRate' : bigint,
  'userId' : Principal,
  'improvements' : Array<string>,
  'createdAt' : bigint,
  'fileName' : string,
  'highlightSkills' : Array<string>,
  'reportRequested' : boolean,
  'atsScore' : bigint,
  'linkedinTips' : Array<string>,
  'competencies' : Array<string>,
  'linkedinUrl' : string,
  'pdfGenerated' : boolean,
}
export interface Testimonial {
  'id' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'text' : string,
  'profession' : string,
  'approved' : boolean,
}
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addJobSource' : ActorMethod<[JobSource], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addVaga' : ActorMethod<[JobListing], undefined>,
  'approveTestimonial' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteExpiredVagas' : ActorMethod<[], bigint>,
  'deleteJobSource' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getActiveJobSources' : ActorMethod<[], Array<JobSource>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getJobSources' : ActorMethod<[], Array<JobSource>>,
  'getLastUpdateTime' : ActorMethod<[], bigint>,
  'getMyResumes' : ActorMethod<[], Array<Resume>>,
  'getPaymentConfig' : ActorMethod<[], [] | [PaymentConfig]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVagas' : ActorMethod<[], Array<JobListing>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAdmin' : ActorMethod<[Principal], undefined>,
  'requestReport' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePaymentConfig' : ActorMethod<[PaymentConfig], undefined>,
  'saveResume' : ActorMethod<[Resume], undefined>,
  'submitTestimonial' : ActorMethod<[Testimonial], undefined>,
  'triggerWeeklyUpdate' : ActorMethod<[], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateJobSource' : ActorMethod<[JobSource], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateResumeReportStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];